/* 
 * author: Joel Klimont
 * filename: player.h
 * date: 23/02/19 
 * matrNr: i14083
 * class: 5CHIF
*/

#ifndef ROBOCODE_PLAYER_H
#define ROBOCODE_PLAYER_H

#include <utility>
#include "messages.pb.h"
#include "game_objects.h"
#undef OK

/*
 * Right now this is just an example.
 * Modify this file as you wish and create your own robot
 * in doing so. Only the arguments and return values of the
 * constructor and the tick function should not be changed!
 */

class Player {
public:
    GameObjects::BasicRobot robot;
    /*!
     * Do not change this constructor!
     * @param robot generated by the server
     */
    explicit Player(GameObjects::BasicRobot robot) : robot(std::move(robot)) {};

    int at_wall = -1;
    int shoot = 20;

    /// Act on the update from the server and set a new position or whatever
    /// the players wants the robot to do!
    /// \param scanned information about the scanned robot
    /// \param hit_wall
        /*! 1 is left \n
         2 is top \n
         3 is right \n
         4 is down
         */
    /// \return true if robot should shoot
    bool tick(GameObjects::BasicRobot* scanned, std::vector<int> hit_wall) {
        bool shot = false;

        //if (shoot == 0) {
        //    shoot = 2;
        //    shot = true;
        //} else {
        //    shoot -= 1;
        //}

        // find first wall
        if (at_wall == -1) {
            this->robot.set_speed(1, 0);

            if (! hit_wall.empty()) {
                at_wall = hit_wall.at(0);

                this->robot.set_speed(0, -1);
            }
            return shot;
        }

        // cycle along walls
        if (! hit_wall.empty()) {
            int wall = 0;
            for (int possible_new_hit: hit_wall) {
                if (possible_new_hit != at_wall) {
                    wall = possible_new_hit;
                }
            }

            if (wall == 1 && wall != at_wall) {
                at_wall = wall;
                this->robot.set_speed(-1, 0);

            } else if (wall == 2 && wall != at_wall) {
                at_wall = wall;
                this->robot.set_speed(0, 1);

            } else if (wall == 3 && wall != at_wall) {
                at_wall = wall;
                this->robot.set_speed(1, 0);

            } else if (wall == 4 && wall != at_wall) {
                at_wall = wall;
                this->robot.set_speed(0, -1);
            }
        }

        // if a robot is scanned shoot
        if (scanned != nullptr) {
            shot = true;
        }

        this->robot.gun_degree += 10;
        this->robot.gun_degree = std::fmod(this->robot.gun_degree, 360);
        this->robot.gun_speed = 10;

        return shot;
    };
};

#endif //ROBOCODE_PLAYER_H
